# =============================================================================
# SNS TOPIC — Anomaly Alert Delivery
# =============================================================================
# Purpose : Fan-out delivery channel for anomaly alerts generated by the
#           aggregator Lambda when a sensor's 5-minute average temperature
#           exceeds the configured threshold.
#
# Design Decisions:
#   - Standard topic (not FIFO) — email delivery does not require strict
#     ordering or exactly-once semantics.
#
#   - Encryption at rest using AWS managed KMS key for SNS.
#     Production enhancement: Customer Managed Key (CMK) for compliance
#     environments requiring key rotation and audit trail.
#
#   - Access policy restricts publishing to the topic owner's account only.
#     This prevents unauthorized principals from injecting false alerts.
#
#   - Email subscription is created in Terraform but requires manual
#     confirmation — AWS sends a confirmation email to the subscriber.
#     The subscription remains in "PendingConfirmation" until confirmed.
#
# Well-Architected:
#   - Security     : Topic policy restricts publishers. Encryption at rest.
#   - Reliability  : SNS delivers to confirmed subscribers with retry logic.
#   - Cost         : First 1M publishes/month free. Email delivery is free.
# =============================================================================

resource "aws_sns_topic" "anomaly_alerts" {
  name         = "${var.project_name}-anomaly-alerts"
  display_name = "Streaming Analytics Alerts"

  # Encryption at rest — AWS managed KMS key for SNS
  kms_master_key_id = "alias/aws/sns"

  tags = {
    Name = "${var.project_name}-anomaly-alerts"
  }
}

# -----------------------------------------------------------------------------
# SNS Topic Policy
# Restricts who can publish to this topic and who can subscribe.
# Only the account owner (our Lambda, our alarms) can publish.
# This prevents unauthorized injection of false alerts.
# -----------------------------------------------------------------------------

data "aws_iam_policy_document" "sns_topic_policy" {

  # Allow the topic owner's account to manage the topic fully
  statement {
    sid    = "AllowTopicOwnerFullAccess"
    effect = "Allow"
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
    actions   = ["SNS:*"]
    resources = [aws_sns_topic.anomaly_alerts.arn]
  }

  # Allow CloudWatch Alarms to publish to this topic
  # Required for our 4 pipeline health alarms defined in cloudwatch.tf
  statement {
    sid    = "AllowCloudWatchAlarmsPublish"
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["cloudwatch.amazonaws.com"]
    }
    actions   = ["SNS:Publish"]
    resources = [aws_sns_topic.anomaly_alerts.arn]
    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values   = [data.aws_caller_identity.current.account_id]
    }
  }
}

resource "aws_sns_topic_policy" "anomaly_alerts_policy" {
  arn    = aws_sns_topic.anomaly_alerts.arn
  policy = data.aws_iam_policy_document.sns_topic_policy.json
}

# -----------------------------------------------------------------------------
# Email Subscription
# NOTE: After `terraform apply`, AWS sends a confirmation email to this
# address. The subscription stays in "PendingConfirmation" until the
# recipient clicks the confirmation link. Alerts are NOT delivered until
# the subscription is confirmed.
# -----------------------------------------------------------------------------

resource "aws_sns_topic_subscription" "email_subscription" {
  topic_arn = aws_sns_topic.anomaly_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email

  # Lifecycle note: If you change the email address, Terraform will
  # destroy the old subscription and create a new one requiring
  # re-confirmation.
}
