################################################################################
# PROJECT 1 - DECEMBER 2025 BASELINE INFRASTRUCTURE
# 
# This Terraform configuration captures the working infrastructure of Project1
# as it existed in December 2025, BEFORE any enhancements were added.
#
# Purpose: Documentation, disaster recovery, and reference baseline
# Created: December 2025
# Documented: February 2026
################################################################################

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  
  # S3 Backend - Store Terraform state in S3
  backend "s3" {
    bucket  = "michel-terraform-state-pipeline"
    key     = "production-baseline/terraform.tfstate"
    region  = "us-east-1"
    encrypt = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "Project1-DataPipeline"
      Environment = "Production"
      Baseline    = "December2025"
      ManagedBy   = "Terraform"
    }
  }
}

################################################################################
# S3 BUCKETS
################################################################################

# Bucket 1: Raw Data Storage
# Purpose: Store raw input files (sales_data.csv, customer_demographics.json)
resource "aws_s3_bucket" "raw_data" {
  bucket = "michel-raw-data-pipeline-project1"

  tags = {
    Name        = "Raw Data Bucket"
    Description = "Stores raw CSV and JSON input files for data pipeline"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "raw_data" {
  bucket = aws_s3_bucket.raw_data.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Bucket 2: Processed Data Storage
# Purpose: Store transformed/enriched data in Parquet format
resource "aws_s3_bucket" "processed_data" {
  bucket = "michel-processed-data-pipeline-project1"

  tags = {
    Name        = "Processed Data Bucket"
    Description = "Stores enriched and aggregated data in Parquet format"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "processed_data" {
  bucket = aws_s3_bucket.processed_data.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Bucket 3: Glue Scripts Storage
# Purpose: Store ETL job scripts
resource "aws_s3_bucket" "glue_scripts" {
  bucket = "michel-glue-scripts-pipeline-project1"

  tags = {
    Name        = "Glue Scripts Bucket"
    Description = "Stores Glue ETL job scripts"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "glue_scripts" {
  bucket = aws_s3_bucket.glue_scripts.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Bucket 4: Athena Query Results
# Purpose: Store Athena query results
resource "aws_s3_bucket" "athena_results" {
  bucket = "michel-athena-results-project1-dec2025"

  tags = {
    Name        = "Athena Results Bucket"
    Description = "Stores Athena query results and metadata"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "athena_results" {
  bucket = aws_s3_bucket.athena_results.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Bucket 5: AWS Glue Assets (Auto-generated by AWS)
# Purpose: AWS-managed storage for Glue temporary files and Spark history
# Note: This bucket is created automatically by AWS Glue service
resource "aws_s3_bucket" "glue_assets" {
  bucket = "aws-glue-assets-${var.aws_account_id}-${var.aws_region}"

  tags = {
    Name        = "AWS Glue Assets"
    Description = "AWS-managed bucket for Glue temporary files and Spark logs"
    Note        = "Auto-created by AWS Glue service"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "glue_assets" {
  bucket = aws_s3_bucket.glue_assets.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

################################################################################
# IAM ROLE FOR GLUE
################################################################################

# IAM Role: Glue Service Role
# Purpose: Allow Glue to access S3 buckets and execute ETL jobs
resource "aws_iam_role" "glue_service_role" {
  name        = "Glue-to-Access-S3-Role-December2025"
  description = "IAM role for AWS Glue to access S3 and execute ETL jobs"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "glue.amazonaws.com"
        }
      }
    ]
  })

  tags = {
    Name = "Glue Service Role"
  }
}

# Attach AWS managed policy: AWSGlueServiceRole
resource "aws_iam_role_policy_attachment" "glue_service_role_policy" {
  role       = aws_iam_role.glue_service_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
}

# Attach AWS managed policy: AmazonS3FullAccess
# Note: For production, this should be replaced with least-privilege bucket-level policies
resource "aws_iam_role_policy_attachment" "glue_s3_access" {
  role       = aws_iam_role.glue_service_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonS3FullAccess"
}

################################################################################
# GLUE DATABASES
################################################################################

# Glue Database 1: Raw Data Catalog
# Purpose: Catalog for raw input data (sales_data.csv, customer_demographics.json)
resource "aws_glue_catalog_database" "sales_pipeline_db" {
  name        = "project1_sales_pipeline_db_december2025"
  description = "Database for AWS data pipeline project1"

  location_uri = "s3://michel-raw-data-pipeline-project1/input/"

  tags = {
    Name = "Project1 Sales Pipeline Database"
  }
}

# Glue Database 2: Processed Data Catalog
# Purpose: Catalog for processed/enriched data
resource "aws_glue_catalog_database" "sales_analytics_db" {
  name        = "project1_sales_analytics_db"
  description = "Database for querying processed sales data"

  location_uri = "s3://michel-processed-data-pipeline-project1/"

  tags = {
    Name = "Project1 Sales Analytics Database"
  }
}

################################################################################
# GLUE CRAWLER
################################################################################

# Glue Crawler: Discover Schema from Raw Data
# Purpose: Automatically detect schema from CSV and JSON files in S3
resource "aws_glue_crawler" "sales_data_crawler" {
  name          = "project1-crawler-data-pipeline-sales-dec2025"
  role          = aws_iam_role.glue_service_role.arn
  database_name = aws_glue_catalog_database.sales_pipeline_db.name
  description   = "project1 crawl your sales and customer data in S3"

  s3_target {
    path = "s3://michel-raw-data-pipeline-project1/input/"
  }

  recrawl_policy {
    recrawl_behavior = "CRAWL_EVERYTHING"
  }

  schema_change_policy {
    update_behavior = "UPDATE_IN_DATABASE"
    delete_behavior = "DEPRECATE_IN_DATABASE"
  }

  lineage_configuration {
    crawler_lineage_settings = "DISABLE"
  }

  configuration = jsonencode({
    Version                = 1.0
    CreatePartitionIndex   = true
  })

  tags = {
    Name = "Project1 Sales Data Crawler"
  }
}

################################################################################
# GLUE CATALOG TABLES
################################################################################

# Note: The following tables are created by the crawler automatically:
# - sales_data_csv
# - customer_demographics_json
#
# The following tables are created manually in Athena:
# - enriched_sales
# - sales_summary
#
# For documentation purposes, we define the manually-created tables here:

# Table 1: Enriched Sales (Manually Created in Athena)
# Purpose: Store enriched sales data with customer demographics
resource "aws_glue_catalog_table" "enriched_sales" {
  name          = "enriched_sales"
  database_name = aws_glue_catalog_database.sales_analytics_db.name
  description   = "Enriched sales data joined with customer demographics"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"         = "parquet"
    "compressionType"        = "snappy"
    "typeOfData"            = "file"
    "EXTERNAL"              = "TRUE"
    "parquet.compression"   = "SNAPPY"
  }

  storage_descriptor {
    location      = "s3://michel-processed-data-pipeline-project1/enriched/"
    input_format  = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
    }

    columns {
      name = "transaction_id"
      type = "string"
    }

    columns {
      name = "date"
      type = "string"
    }

    columns {
      name = "customer_id"
      type = "string"
    }

    columns {
      name = "product"
      type = "string"
    }

    columns {
      name = "quantity"
      type = "bigint"
    }

    columns {
      name = "unit_price"
      type = "double"
    }

    columns {
      name = "region"
      type = "string"
    }

    columns {
      name = "total_amount"
      type = "double"
    }

    columns {
      name = "age_group"
      type = "string"
    }

    columns {
      name = "membership_tier"
      type = "string"
    }

    columns {
      name = "signup_date"
      type = "string"
    }

    columns {
      name = "year"
      type = "bigint"
    }

    columns {
      name = "month"
      type = "bigint"
    }

    columns {
      name = "day"
      type = "bigint"
    }
  }

  partition_keys {
    name = "year"
    type = "bigint"
  }

  partition_keys {
    name = "month"
    type = "bigint"
  }
}

# Table 2: Sales Summary (Manually Created in Athena)
# Purpose: Pre-aggregated summary statistics
resource "aws_glue_catalog_table" "sales_summary" {
  name          = "sales_summary"
  database_name = aws_glue_catalog_database.sales_analytics_db.name
  description   = "Aggregated sales summary by region, product, and time"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"         = "parquet"
    "compressionType"        = "snappy"
    "typeOfData"            = "file"
    "EXTERNAL"              = "TRUE"
    "parquet.compression"   = "SNAPPY"
  }

  storage_descriptor {
    location      = "s3://michel-processed-data-pipeline-project1/summary/"
    input_format  = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
    }

    columns {
      name = "region"
      type = "string"
    }

    columns {
      name = "product"
      type = "string"
    }

    columns {
      name = "year"
      type = "bigint"
    }

    columns {
      name = "month"
      type = "bigint"
    }

    columns {
      name = "total_revenue"
      type = "double"
    }

    columns {
      name = "transaction_count"
      type = "bigint"
    }

    columns {
      name = "avg_transaction_value"
      type = "double"
    }
  }
}

################################################################################
# GLUE ETL JOB
################################################################################

# Glue ETL Job: Transform and Enrich Data
# Purpose: Join sales with customer data, create aggregations, partition output
resource "aws_glue_job" "sales_etl_pipeline" {
  name              = "sales-ETL-Pipeline-dec2025"
  description       = "ETL pipeline that joins sales and customer data, creates aggregated summaries"
  role_arn          = aws_iam_role.glue_service_role.arn
  glue_version      = "5.0"
  worker_type       = "G.1X"
  number_of_workers = 2
  max_retries       = 0
  timeout           = 10
  execution_class   = "STANDARD"

  command {
    name            = "glueetl"
    script_location = "s3://aws-glue-assets-${var.aws_account_id}-${var.aws_region}/scripts/sales-ETL-Pipeline-dec2025.py"
    python_version  = "3"
  }

  default_arguments = {
    "--enable-metrics"          = "true"
    "--enable-job-insights"     = "true"
    "--enable-glue-datacatalog" = "true"
    "--job-bookmark-option"     = "job-bookmark-disable"
    "--job-language"            = "python"
    "--spark-event-logs-path"   = "s3://aws-glue-assets-${var.aws_account_id}-${var.aws_region}/sparkHistoryLogs/"
    "--TempDir"                 = "s3://aws-glue-assets-${var.aws_account_id}-${var.aws_region}/temporary/"
  }

  execution_property {
    max_concurrent_runs = 1
  }

  tags = {
    Name = "Project1 Sales ETL Pipeline"
  }
}

################################################################################
# CLOUDWATCH MONITORING (AUTO-CREATED BY AWS)
################################################################################

# Note: AWS Glue automatically creates CloudWatch log groups for monitoring
# No Terraform configuration needed - documented here for reference
#
# Automatically created log groups:
# - /aws-glue/jobs/output        - Glue job output logs
# - /aws-glue/jobs/error         - Glue job error logs  
# - /aws-glue/crawlers           - Crawler execution logs
#
# To view logs:
# AWS Console → CloudWatch → Log Groups → Search for job/crawler name
#
# Log retention: Default 30 days (can be configured if needed)
# Cost: Free tier includes 5GB of log ingestion and storage
#
# For the Glue ETL job: sales-ETL-Pipeline-dec2025
# - Output logs: /aws-glue/jobs/output
# - Error logs: /aws-glue/jobs/error
#
# For the Crawler: project1-crawler-data-pipeline-sales-dec2025
# - Logs: /aws-glue/crawlers

################################################################################
# OUTPUTS
################################################################################

output "s3_bucket_raw_data" {
  description = "S3 bucket for raw input data"
  value       = aws_s3_bucket.raw_data.id
}

output "s3_bucket_processed_data" {
  description = "S3 bucket for processed/enriched data"
  value       = aws_s3_bucket.processed_data.id
}

output "glue_database_raw" {
  description = "Glue database for raw data catalog"
  value       = aws_glue_catalog_database.sales_pipeline_db.name
}

output "glue_database_analytics" {
  description = "Glue database for analytics"
  value       = aws_glue_catalog_database.sales_analytics_db.name
}

output "glue_crawler_name" {
  description = "Glue crawler name"
  value       = aws_glue_crawler.sales_data_crawler.name
}

output "glue_job_name" {
  description = "Glue ETL job name"
  value       = aws_glue_job.sales_etl_pipeline.name
}

output "iam_role_arn" {
  description = "IAM role ARN for Glue"
  value       = aws_iam_role.glue_service_role.arn
}
